"""
Request Models

Defines all request schemas accepted by Vidhi API endpoints.
Uses Pydantic for validation and documentation.
"""

from typing import Optional, Dict, List
from pydantic import BaseModel, Field


# -------------------------------------------------------------------
# Base Request (shared by all workflows)
# -------------------------------------------------------------------

class BaseRequest(BaseModel):
    """
    Common fields shared across all API requests.
    """

    request_id: str = Field(
        ...,
        description="Unique request identifier generated by the client",
        example="REQ-2026-0001",
    )

    user_id: Optional[str] = Field(
        None,
        description="Optional user identifier (hashed or anonymized)",
        example="user_abc123",
    )

    jurisdiction: str = Field(
        ...,
        description="Legal jurisdiction for the case",
        example="India",
    )

    case_type: str = Field(
        ...,
        description="Type of legal case",
        example="Bail",
    )

    constraints: Optional[Dict[str, str]] = Field(
        default_factory=dict,
        description="Optional user constraints (time, format, language, etc.)",
        example={"time_sensitive": "true"},
    )


# -------------------------------------------------------------------
# Research Workflow Request
# -------------------------------------------------------------------

class ResearchRequest(BaseRequest):
    """
    Request model for legal research workflows.
    """

    case_context: str = Field(
        ...,
        description="Narrative description of the legal case or facts",
        example="Accused arrested under NDPS Act with small quantity.",
    )

    preferred_sources: Optional[List[str]] = Field(
        default_factory=list,
        description="Optional list of preferred legal sources",
        example=["Supreme Court", "High Court"],
    )


# -------------------------------------------------------------------
# Document Generation Workflow Request
# -------------------------------------------------------------------

class DocumentGenerationRequest(BaseRequest):
    """
    Request model for legal document drafting.
    """

    document_type: str = Field(
        ...,
        description="Type of legal document to generate",
        example="Bail Application",
    )

    research_reference_id: Optional[str] = Field(
        None,
        description="Reference to prior research request (if any)",
        example="REQ-2026-0001",
    )

    facts: str = Field(
        ...,
        description="Facts to be incorporated into the legal document",
        example="The accused has no prior criminal record...",
    )

    tone: Optional[str] = Field(
        "formal",
        description="Tone of the generated document",
        example="formal",
    )


# -------------------------------------------------------------------
# Compliance Check Workflow Request
# -------------------------------------------------------------------

class ComplianceCheckRequest(BaseRequest):
    """
    Request model for compliance and risk checks.
    """

    document_text: str = Field(
        ...,
        description="Generated or uploaded legal document text",
    )

    check_types: Optional[List[str]] = Field(
        default_factory=lambda: [
            "hallucination",
            "citation_accuracy",
            "ethical_risk",
        ],
        description="Types of compliance checks to perform",
    )


# -------------------------------------------------------------------
# Feedback / Review Request
# -------------------------------------------------------------------

class FeedbackRequest(BaseModel):
    """
    Captures user or human reviewer feedback.
    """

    request_id: str = Field(
        ...,
        description="Request ID being reviewed",
        example="REQ-2026-0001",
    )

    rating: Optional[int] = Field(
        None,
        ge=1,
        le=5,
        description="Optional rating (1–5)",
    )

    comments: Optional[str] = Field(
        None,
        description="Reviewer comments or corrections",
    )

    requires_followup: bool = Field(
        False,
        description="Whether further human or agent action is required",
    )
